---
apiVersion: ksail.io/v1alpha1
kind: Cluster
metadata:
  # The name of the KSail object. [default: ksail-default]
  name: ksail-default
# The spec of the KSail Cluster object.
spec:
  mirrorRegistries:
  - # A proxy for the registry to use to proxy and cache images.
    proxy:
      # The URL of the upstream registry to proxy and cache images from. [default: https://registry-1.docker.io]
      url: https://registry.k8s.io/
    # The name of the registry. [default: ksail-registry]
    name: registry.k8s.io-proxy
    # The host port of the registry (if applicable). [default: 5555]
    hostPort: 5556
  - # A proxy for the registry to use to proxy and cache images.
    proxy:
      # The URL of the upstream registry to proxy and cache images from. [default: https://registry-1.docker.io]
      url: https://registry-1.docker.io/
    # The name of the registry. [default: ksail-registry]
    name: docker.io-proxy
    # The host port of the registry (if applicable). [default: 5555]
    hostPort: 5557
  - # A proxy for the registry to use to proxy and cache images.
    proxy:
      # The URL of the upstream registry to proxy and cache images from. [default: https://registry-1.docker.io]
      url: https://ghcr.io/
    # The name of the registry. [default: ksail-registry]
    name: ghcr.io-proxy
    # The host port of the registry (if applicable). [default: 5555]
    hostPort: 5558
  - # A proxy for the registry to use to proxy and cache images.
    proxy:
      # The URL of the upstream registry to proxy and cache images from. [default: https://registry-1.docker.io]
      url: https://gcr.io/
    # The name of the registry. [default: ksail-registry]
    name: gcr.io-proxy
    # The host port of the registry (if applicable). [default: 5555]
    hostPort: 5559
  - # A proxy for the registry to use to proxy and cache images.
    proxy:
      # The URL of the upstream registry to proxy and cache images from. [default: https://registry-1.docker.io]
      url: https://mcr.microsoft.com/
    # The name of the registry. [default: ksail-registry]
    name: mcr.microsoft.com-proxy
    # The host port of the registry (if applicable). [default: 5555]
    hostPort: 5560
  - # A proxy for the registry to use to proxy and cache images.
    proxy:
      # The URL of the upstream registry to proxy and cache images from. [default: https://registry-1.docker.io]
      url: https://quay.io/
    # The name of the registry. [default: ksail-registry]
    name: quay.io-proxy
    # The host port of the registry (if applicable). [default: 5555]
    hostPort: 5561
